### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by mackdosh** [cosminmocan/vfio-single-amdgpu-passthrough#2]
Hello, I do not use github often so I do not know if this is where I post questions. I am trying to do single amdgpu passthrough and I am sure that I have everything set correctly in my files. I have already updated grub, I did everything correctly for the virt-manager qemu vm. It must have something to do with my start file, but I do not see the issue. I also, can not ssh in to find the issue. Basically, when I start the vm the screen goes black, then I see my TTY with the x org process killing itself, then my monitor goes blue, then the screen goes black and nothing happens after. I am using gentoo linux so my files may be different than someone on ubuntu, just saying. Here is my start script, which I blurred some info which is just the linux username and my detach ids which are set correctly so no worries about those. 

![image](https://user-images.githubusercontent.com/82271783/114332797-e9da9680-9b14-11eb-8788-5e7a8b30a9af.png)

Edit: I forgot to mention my gpu is the Rx 550, my cpu is the AMD 5 5600x, and I am using DWM as my window manager

**Comment by cosminmocan** [comment]
Remove the line under # Unbind EFI-Framebuffer.

Sorry for the late reply

**Comment by Swyter** [comment]
In my case it was because I was booting the host system with _Compatibility Support Module_ (CSM) enabled, i.e. the legacy BIOS. By booting my Linux install with a plain UEFI bootloader (*after* ensuring CSM is completely disabled) it worked straight away.

Even if you boot via EFI it won't work if CSM is enabled.

These errors in `dmesg` were driving me crazy even if the configuration was perfect:
```
vfio-pci 0000:03:00.0: No more image in the PCI ROM
vfio_ecap_init: hiding ecap 0x19@0x270
```

 Hope it helps anyone else finding this through a search engine, it would have come in handy three hours ago.
